parameters:
  buildConfiguration: 'Release'
  hasUnitTests: 'false'

steps:
- script: dotnet restore
  displayName: Restoring .Net packages

- script: dotnet build --configuration ${{ parameters.buildConfiguration }}
  displayName: Building .Net code

- ${{ if eq(parameters.hasUnitTests, 'true') }}:
  - task: DotNetCoreCLI@2
    displayName: Running unit tests
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration ${{ parameters.buildConfiguration }}'
      
 - script: dotnet publish ${{ parameters.appName }} --configuration ${{ parameters.buildConfiguration }} --output publish/
 displayName: Packing application ${{ parameters.appName }}

  - task: CopyFiles@2
  displayName: Copy packed application ${{ parameters.appName }} to output
  inputs:
    contents: |
      ${{ parameters.appName }}/publish/**
      !**/appsettings.Development.json
    targetFolder: '$(Build.ArtifactStagingDirectory)/${{ parameters.artifactFolder }}'
    flattenFolders: true
